server:
  port: 7001
  servlet:
    context-path: /ad-search

spring:
  application:
    name: eureka-client-ad-search
  datasource:
    url: jadb:mysql://192.168.0.104:3306/ad_data?autoReconnect=true
    username: root
    password: 123456
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: ture
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

#使用feign访问其他微服务
feign:
  hystrix:
    enabled: true

#服务的监控
management:
  endpoints:
    web:
      exposure:
        include: "*"

adconf:
  mysql:
    host: 192.168.0.104
    port: 3306
    username: root
    password: 123456
    binlogName: ""
    position: -1
